### ISSUE TITLE
Handle error when Thoth login credentials are not provided

### ISSUE THREAD

**Issue by lb803** [OpenBookPublishers/cit-ex#1]
This call throws a not-so-clear error when login credentials are not provided
https://github.com/OpenBookPublishers/cit-ex/blob/dad3a67109d8a18d1afebc3fc24eeec16e9302a7/cit-ex/lib/repository.py#L46

```
[...]
thothlibrary.errors.ThothError: GraphQL Error.
Request:
https://api.thoth.pub/account/login

Response:
<Response [400]>
[...]
```

Would be nice to improve this by offering more info about what went wrong

**Comment by rhigman** [comment]
Added defensive code under a1704a4 which raises an error message instead of attempting login if credentials are unset.

Note that when calling from `obp-loader.py`, the error message is still not very readable because of the way the subprocess failure is handled (see below). This is the case for all errors raised from within `main.py` rather than `obp-loader.py` itself. Might be nice to rewrite the wrapper command to avoid subprocesses.

```
Traceback (most recent call last):
  File "/home/obp/cit-ex/main.py", line 105, in <module>
    main()
  File "/home/obp/cit-ex/main.py", line 90, in main
    raise KeyError(f"No Thoth username provided")
KeyError: 'No Thoth username provided'
Executing: `python3 main.py /tmp/tmpr_921kpn -c bibliography-first-para bibliography-other-para -i https://doi.org/10.11647/OBP.0331.06`
Traceback (most recent call last):
  File "/home/obp/cit-ex/obp-loader.py", line 146, in <module>
    main()
  File "/home/obp/cit-ex/obp-loader.py", line 61, in main
    subprocess.check_output(cmd.split())
  File "/usr/local/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python3', 'main.py', '/tmp/tmpr_921kpn', '-c', 'bibliography-first-para', 'bibliography-other-para', '-i', 'https://doi.org/10.11647/OBP.0331.06']' returned non-zero exit status 1.
```
